name: Daily Run 

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch: 

jobs:
  run_app:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Set up environment variables
      run: |
        echo "NOTION_API_SECRET=${{ secrets.NOTION_API_SECRET }}" >> $GITHUB_ENV
        echo "OPEN_AI_SECRET=${{ secrets.OPEN_AI_SECRET }}" >> $GITHUB_ENV
        echo "DATABASE_ID=${{ secrets.DATABASE_ID }}" >> $GITHUB_ENV

    - name: Run the app
      run: npm start
